"""add receiver_phone and delivery_code to orders

Revision ID: 57af0cf70cd7
Revises: c02e25b9f348
Create Date: 2026-05-08 10:51:01.511444

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57af0cf70cd7'
down_revision: Union[str, Sequence[str], None] = 'c02e25b9f348'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('receiver_phone', sa.String(length=30), nullable=True))
    op.add_column('orders', sa.Column('delivery_code', sa.String(length=10), nullable=True))
    op.add_column('orders', sa.Column('delivery_code_expires_at', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'delivery_code_expires_at')
    op.drop_column('orders', 'delivery_code')
    op.drop_column('orders', 'receiver_phone')
    # ### end Alembic commands ###
