"""add fcm_token to rider_profile

Revision ID: 7354cd484457
Revises: 57af0cf70cd7
Create Date: 2026-05-08 11:36:54.050180

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7354cd484457'
down_revision: Union[str, Sequence[str], None] = '57af0cf70cd7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'receiver_phone',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
    op.add_column('rider_profiles', sa.Column('fcm_token', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rider_profiles', 'fcm_token')
    op.alter_column('orders', 'receiver_phone',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    # ### end Alembic commands ###
