"""add order_type and services fields

Revision ID: b4022563c400
Revises: 7683b65ab03f
Create Date: 2026-05-14 12:24:52.887681

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4022563c400'
down_revision: Union[str, Sequence[str], None] = '7683b65ab03f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('order_type', sa.String(length=20), nullable=False, server_default='delivery'))
    op.alter_column('orders', 'receiver_phone',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    op.add_column('rider_profiles', sa.Column('services', sa.String(length=50), nullable=False, server_default='delivery'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rider_profiles', 'services')
    op.alter_column('orders', 'receiver_phone',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
    op.drop_column('orders', 'order_type')
    # ### end Alembic commands ###
