"""add payment fields to orders

Revision ID: e90e2c2d0759
Revises: 7354cd484457
Create Date: 2026-05-08 22:45:15.467515

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e90e2c2d0759'
down_revision: Union[str, Sequence[str], None] = '7354cd484457'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('amount', sa.Float(), nullable=True))
    op.add_column('orders', sa.Column('commission', sa.Float(), nullable=True))
    op.add_column('orders', sa.Column('payment_method', sa.String(length=30), nullable=True))
    op.add_column('orders', sa.Column('payment_status', sa.String(length=30), nullable=True, server_default='pending'))
    op.add_column('orders', sa.Column('payment_confirmed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'payment_confirmed_at')
    op.drop_column('orders', 'payment_status')
    op.drop_column('orders', 'payment_method')
    op.drop_column('orders', 'commission')
    op.drop_column('orders', 'amount')
    # ### end Alembic commands ###
